### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hfossli** [chrisamanse/Changes#1]
Hey

I just saw this project on twitter from the cocoapods feed.

I don't know how much of the code is overlapping or how much / how little is taken from https://github.com/osteslag/Changeset, but I do think if there is _any_ code at all you should comply to the license specified in that project. I have no relation to Changeset or the author. I just think it is a good sport to respect the licenses.

> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> - Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

If you have any code at all (modified or not modified) taken/borrowed from Changeset
- you should comply to the license specified in Changeset
- or you can ask him if he is willing to change to MIT

If you don't have any code at all (modified or not modified) taken/borrowed from Changeset then I'm sorry to have wasted your time :-) 

I really like the MIT license is a lot better than the BSD-2 so I hope I'm wrong or that the author of Changeset will switch to MIT.

**Comment by chrisamanse** [comment]
Hi,

Yes, the project was inspired by [Changeset](https://github.com/osteslag/Changeset) as stated in the [Readme](https://github.com/chrisamanse/Changes/tree/master/README.md) in the repo. I've read the code of Changeset as well and found where he got the algorithm. It's available in [Wikipedia](https://en.wikipedia.org/wiki/Wagner–Fischer_algorithm) and explained further by a blog post he [cited](http://davedelong.tumblr.com/post/134367865668/edit-distance-and-edit-steps).

The public APIs are different but the algorithm, which is the core component of the project, used is the same. I honestly don't know if it's considered as a modification since implementing the same algorithm (especially the pseudocode based on Wikipedia) will result to a very similar code structure. However, the project was built from scratch.

Perhaps, I should coordinate with Changeset's author.

Thank you for bringing up this issue :)

**Comment by hfossli** [comment]
Cool! Thanks for being so approachable! Awesome.

Hard for me to say if this is a violation or not. Anyway, I think it is a good idea to give him a heads up. I'm guessing he will be a good sport and grant you the rights to license your lib under MIT without including his BSD-2 license. 

As you say, it is hard to implement the same algorithm and at the same time end up with different code.

**Comment by hfossli** [comment]
Awesome

**Comment by osteslag** [comment]
Thanks for bringing this up, @hfossli. I thought the two licences were practically identical, but clearly not quite.

The license of [Changeset v1.0.3](https://github.com/osteslag/Changeset/releases/tag/v1.0.3) and going forward is now MIT. That should clear up this licensing issue.

I appreciate the attribution in your README, @chrisamanse. Thank you.

**Comment by chrisamanse** [comment]
:+1: @osteslag No problem.
